# Generated by Django 4.2 on 2023-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lessonid', models.AutoField(db_column='lessonID', primary_key=True, serialize=False)),
                ('lesson_date', models.DateField()),
                ('topic', models.TextField()),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('wordid', models.AutoField(db_column='wordID', primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('translation', models.TextField()),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
    ]
